Repository Hypance/HypanceDataAnalysis, pull requests merged in 2023-04, with the labels that each got.

#119 Ugur.Black
  Tests/files/WilliamR.xlsx
  Tests/test_hma.py
  Tests/test_ichimoku_cloud.py
  Tests/test_momentum.py
  Tests/test_on_balance_volume.py
  Tests/test_williams_r.py
  Tests/test_wma.py
  hyta/hma.py
  hyta/ichimoku_cloud.py
  hyta/momentum.py
  hyta/on_balance_volume.py
  hyta/williams_r.py
  hyta/wma.py
Labels: documentation

#111 Bahar.black
  Tests/test_adx.py
  Tests/test_cmf.py
  Tests/test_dx.py
  Tests/test_mfi.py
  Tests/test_ppo.py
  hyta/adx.py
  hyta/cmf.py
  hyta/dx.py
  hyta/mfi.py
Labels: enhancement

#106 Aroon-fixed
  Tests/files/Aroon.Oscillator.xls
  Tests/test_Aroon.py
  hyta/aroon.py
Labels: enhancement

#107 rsi-fixed
  .gitignore
  Tests/files/RSI.xlsx
  Tests/test_rsi.py
  hyta/rsi.py
Labels: enhancement

#123 indicators and tests run by black
  Tests/test_bollinger.py
  Tests/test_ema.py
  Tests/test_kama.py
  hyta/bollinger.py
  hyta/ema.py
  hyta/kama.py
Labels: enhancement

#104 t3tillson-fixed
  .gitignore
  Tests/files/t3tillson.xlsx
  Tests/test_t3.py
  hyta/t3tillson.py
Labels: enhancement

#127 uo test is fixed and linted
  Tests/test_uo.py
  hyta/uo.py
Labels: bug

#66 dema, test and file
  Tests/files/dema.xlsx
  Tests/test_dema.py
  hyta/dema.py
Labels: enhancement

#130 kama updated
  hyta/kama.py
Labels: enhancement

#129 fixed and linted
  Tests/test_dpo.py
  Tests/test_macd.py
  Tests/test_ppo.py
  Tests/test_psar.py
  Tests/test_roc.py
  Tests/test_tma.py
  hyta/dpo.py
  hyta/macd.py
  hyta/ppo.py
  hyta/psar.py
  hyta/roc.py
  hyta/tma.py
Labels: bug
